services:
  transcrybe:
    image: ghcr.io/kiarc/transcrybe:latest # Or specify a version
    ports:
      - 8000:8000
    environment:
      TRANSCRYBE_HF_TOKEN: PLEASE_ADD_A_TOKEN # This is mandatory. See the pyannote.audio repository for more info on how to configure the token.
      TRANSCRYBE_MODEL_SIZE: base.en # This one is optional, and this is the default value
    restart: unless-stopped
