name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and publish docker image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: kiarc
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: ghcr.io
        image_name: transcrybe
        image_tag: latest,"${{ github.ref_name }}"
