name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Free up space
      uses: easimon/maximize-build-space@master
      with:
        # We need space at /var/docker for the image to be built to
        root-reserve-mb: 32768
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-codeql: 'true'
    - uses: actions/checkout@v4
    - name: Build and publish docker image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: kiarc
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: ghcr.io
        image_name: transcrybe
        image_tag: latest,${{ github.ref_name }}
